import { execFileSync } from 'node:child_process'
import type { Plugin } from 'vite'
import { faqItems } from '../src/content/faq.ts'
import { DEFAULT_SITE_URL, disallowedUserAgents, seo, sitemapRoutes } from '../src/content/seo.ts'
import { site } from '../src/content/site.ts'

/**
 * Build-time SEO. Everything a crawler reads before it runs a line of
 * JavaScript — the head tags, the JSON-LD graph, robots.txt and sitemap.xml —
 * is generated here from `src/content/seo.ts`, so the copy has exactly one
 * home and the absolute URLs can never drift from where the site is deployed.
 */

export interface SeoContext {
  /** Canonical origin plus path, always with a trailing slash. */
  readonly siteUrl: string
  /** Vite's base path, always with a trailing slash. */
  readonly base: string
  /** ISO date used as `lastmod` in the sitemap. */
  readonly lastModified: string
}

/** Appends the trailing slash a base URL needs for `new URL()` to resolve against it. */
const withTrailingSlash = (value: string): string => (value.endsWith('/') ? value : `${value}/`)

/**
 * The deploy workflow passes the URL GitHub Pages reports, which already covers
 * both a project site (`/<repo>/`) and a custom domain. Local builds fall back
 * to the published address so previews show the real canonical tags.
 */
export const resolveSiteUrl = (env: Record<string, string | undefined>): string => {
  const configured = env.SITE_URL?.trim()
  return withTrailingSlash(configured && configured !== '' ? configured : DEFAULT_SITE_URL)
}

/** Resolves a site-relative path against the canonical URL. */
export const absoluteUrl = (siteUrl: string, path = ''): string => new URL(path, siteUrl).href

/**
 * `lastmod` should track the content, not the clock, so it comes from the last
 * commit. A build outside a git checkout falls back to the build date.
 */
export const resolveLastModified = (cwd: string): string => {
  try {
    const committed = execFileSync('git', ['log', '-1', '--format=%cI'], {
      cwd,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim()

    if (committed !== '') return committed.slice(0, 10)
  } catch {
    // Not a git checkout — fall through to the build date.
  }

  return new Date().toISOString().slice(0, 10)
}

const escapeXml = (value: string): string =>
  value.replace(/[<>&'"]/g, (char) => {
    switch (char) {
      case '<':
        return '&lt;'
      case '>':
        return '&gt;'
      case '&':
        return '&amp;'
      case "'":
        return '&apos;'
      default:
        return '&quot;'
    }
  })

const escapeHtml = (value: string): string =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

export const buildRobotsTxt = ({ siteUrl }: SeoContext): string =>
  [
    '# https://www.robotstxt.org/robotstxt.html',
    '# Generated by vite/seo.ts — edit src/content/seo.ts instead.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    '# SEO scrapers that resell the crawl rather than send visitors.',
    ...disallowedUserAgents.flatMap((agent) => [`User-agent: ${agent}`, 'Disallow: /', '']),
    `Sitemap: ${absoluteUrl(siteUrl, 'sitemap.xml')}`,
    '',
  ].join('\n')

export const buildSitemapXml = ({ siteUrl, lastModified }: SeoContext): string => {
  const entries = sitemapRoutes.map((route) =>
    [
      '  <url>',
      `    <loc>${escapeXml(absoluteUrl(siteUrl, route.path))}</loc>`,
      `    <lastmod>${lastModified}</lastmod>`,
      `    <changefreq>${route.changefreq}</changefreq>`,
      `    <priority>${route.priority.toFixed(1)}</priority>`,
      '  </url>',
    ].join('\n'),
  )

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries,
    '</urlset>',
    '',
  ].join('\n')
}

/**
 * One `@graph` rather than several isolated scripts, so the entries can point
 * at each other by `@id` and search engines read them as one description of
 * one page.
 */
export const buildStructuredData = ({ siteUrl }: SeoContext): string => {
  const websiteId = `${siteUrl}#website`
  const authorId = `${siteUrl}#author`
  const imageUrl = absoluteUrl(siteUrl, seo.socialImage.path)

  return JSON.stringify({
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Person',
        '@id': authorId,
        name: seo.author.name,
        url: seo.author.url,
      },
      {
        '@type': 'WebSite',
        '@id': websiteId,
        url: siteUrl,
        name: site.name,
        description: seo.description,
        inLanguage: seo.language,
        publisher: { '@id': authorId },
      },
      {
        '@type': 'WebPage',
        '@id': `${siteUrl}#webpage`,
        url: siteUrl,
        name: seo.title,
        description: seo.description,
        isPartOf: { '@id': websiteId },
        about: { '@id': `${siteUrl}#app` },
        primaryImageOfPage: imageUrl,
        inLanguage: seo.language,
      },
      {
        '@type': 'SoftwareApplication',
        '@id': `${siteUrl}#app`,
        name: seo.application.name,
        description: site.description,
        url: siteUrl,
        image: imageUrl,
        applicationCategory: seo.application.category,
        operatingSystem: seo.application.operatingSystems.join(', '),
        author: { '@id': authorId },
        license: seo.application.license,
        isAccessibleForFree: true,
        offers: {
          '@type': 'Offer',
          price: '0',
          priceCurrency: 'USD',
        },
        softwareHelp: site.docs.beginnerGuide,
        sameAs: Object.values(site.repositories),
      },
      {
        '@type': 'FAQPage',
        '@id': `${siteUrl}#faq`,
        isPartOf: { '@id': websiteId },
        mainEntity: faqItems.map((item) => ({
          '@type': 'Question',
          name: item.question,
          acceptedAnswer: { '@type': 'Answer', text: item.answer },
        })),
      },
    ],
  })
}

/**
 * The head tags every crawler and social scraper reads. Written as raw HTML
 * rather than through Vite's tag descriptors so the order — and therefore the
 * diff a reviewer sees in `dist/index.html` — stays readable.
 */
export const buildHeadTags = (context: SeoContext): string => {
  const { siteUrl, base } = context
  const imageUrl = absoluteUrl(siteUrl, seo.socialImage.path)

  const tags: readonly string[] = [
    `<title>${escapeHtml(seo.title)}</title>`,
    `<meta name="description" content="${escapeHtml(seo.description)}" />`,
    `<link rel="canonical" href="${siteUrl}" />`,
    '<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />',
    `<meta name="author" content="${escapeHtml(seo.author.name)}" />`,
    `<meta name="application-name" content="${escapeHtml(site.name)}" />`,
    `<meta name="theme-color" content="${seo.themeColor}" />`,
    '<meta name="color-scheme" content="dark" />',
    '',
    '<meta property="og:type" content="website" />',
    `<meta property="og:site_name" content="${escapeHtml(site.name)}" />`,
    `<meta property="og:title" content="${escapeHtml(seo.title)}" />`,
    `<meta property="og:description" content="${escapeHtml(seo.description)}" />`,
    `<meta property="og:url" content="${siteUrl}" />`,
    `<meta property="og:locale" content="${seo.locale}" />`,
    `<meta property="og:image" content="${imageUrl}" />`,
    `<meta property="og:image:type" content="${seo.socialImage.type}" />`,
    `<meta property="og:image:width" content="${seo.socialImage.width}" />`,
    `<meta property="og:image:height" content="${seo.socialImage.height}" />`,
    `<meta property="og:image:alt" content="${escapeHtml(seo.socialImage.alt)}" />`,
    '',
    '<meta name="twitter:card" content="summary_large_image" />',
    `<meta name="twitter:title" content="${escapeHtml(seo.title)}" />`,
    `<meta name="twitter:description" content="${escapeHtml(seo.description)}" />`,
    `<meta name="twitter:image" content="${imageUrl}" />`,
    `<meta name="twitter:image:alt" content="${escapeHtml(seo.socialImage.alt)}" />`,
    '',
    `<link rel="icon" type="image/svg+xml" href="${base}favicon.svg" />`,
    `<link rel="icon" type="image/png" sizes="96x96" href="${base}favicon-96.png" />`,
    `<link rel="apple-touch-icon" sizes="180x180" href="${base}apple-touch-icon.png" />`,
    `<link rel="sitemap" type="application/xml" href="${absoluteUrl(siteUrl, 'sitemap.xml')}" />`,
    '',
    `<script type="application/ld+json">${buildStructuredData(context)}</script>`,
  ]

  // Blank entries are group separators; trailing indentation on them would
  // only show up as whitespace noise in the built HTML.
  return tags.join('\n    ').replace(/[ \t]+$/gm, '')
}

export const seoPlugin = (): Plugin => {
  let context: SeoContext

  return {
    name: 'sonicrelay-seo',
    enforce: 'pre',

    configResolved(config) {
      context = {
        siteUrl: resolveSiteUrl(process.env),
        base: withTrailingSlash(config.base),
        lastModified: resolveLastModified(config.root),
      }
    },

    transformIndexHtml: {
      order: 'pre',
      handler: (html) => html.replace('<!--seo-->', buildHeadTags(context)),
    },

    generateBundle() {
      this.emitFile({ type: 'asset', fileName: 'robots.txt', source: buildRobotsTxt(context) })
      this.emitFile({ type: 'asset', fileName: 'sitemap.xml', source: buildSitemapXml(context) })
    },
  }
}
